'use strict'

var Netmask = require('netmask').Netmask
var trim_ip_address = require('../helpers/trim_ip_address.js')

exports.main = `# This file is auto-generated by system. Do not edit manually!
auto lo
iface lo inet loopback
`

exports.static = `
auto  [INTERFACE]
allow-hotplug  [INTERFACE]
iface  [INTERFACE]  inet  static
  address  [ADDRESS]
  netmask  [NETMASK]
[NAMESERVERS]
[GATEWAY]
[VLAN]
`
exports.dhcp = `
auto  [INTERFACE]
allow-hotplug  [INTERFACE]
iface  [INTERFACE]  inet  dhcp
[VLAN]
`

exports.ppp = `
auto  [PROVIDER]
iface  [PROVIDER]  inet  ppp
pre-up  /bin/ip  link  set  [PHYSICAL_INTERFACE]  up
provider  [PROVIDER]
`

exports.formatDNS = ns => {
  if (!ns) return '';

  var dns_nameservers = '  dns-nameservers  ';
  var r = /\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}/g

  if (Array.isArray(ns)) {
    var addresses = ns.reduce((result, item) => {
      var addrs = item.match(r)
      if (addrs && addrs.length) {
        return result + ' ' + item.match(r).join(' ')
      } else {
        return result
      }
    }, '').trim()
    return addresses ? dns_nameservers + addresses + '\n' : ''
  } else if (typeof ns === 'string') {
    var addresses = ns.match(r)
    return addresses && addresses.length ? dns_nameservers + addresses.join(' ') + '\n' : ''
  } else {}
}

exports.staticFormat = (config) => {
  var is_vlan = typeof config.vlanid == 'number'
  var ifname = is_vlan
    ? config.ifname
    : config.interface

  var block = new Netmask(`${trim_ip_address(config.ip_address)}/${config.prefix}`)

  return exports.static
    .replace(/\[INTERFACE\]/g, ifname)
    .replace(/\[ADDRESS\]/, trim_ip_address(config.ip_address))
    .replace(/\[NETMASK\]/, block.mask)
    .replace(/\[NAMESERVERS\]\n/, exports.formatDNS(config.nameservers))
    .replace(/\[GATEWAY\]\n/, config.gateway? `  gateway  ${trim_ip_address(config.gateway)}\n`: '')
    .replace(/\[VLAN\]/, is_vlan? `  vlan-raw-device ${config.interface}` : '')
    .trim()
}

exports.dhcpFormat = (config) => {
  var is_vlan = typeof config.vlanid == 'number'
  var ifname = is_vlan
    ? config.ifname
    : config.interface
  return exports.dhcp
    .replace(/\[INTERFACE\]/g, ifname)
    .replace(/\[VLAN\]/, is_vlan? `  vlan-raw-device ${config.interface}` : '')
    .trim()
}

exports.manualFormat = config => {
  var is_vlan = typeof config.vlanid == 'number'
  var iface = is_vlan
    ? config.ifname
    : config.interface

  var ret = `iface ${iface} inet manual`
  return is_vlan
    ? ret + '\n  vlan-raw-device ' + config.interface
    : ret
}

exports.pppformat = config => {
  return exports.ppp
    .replace(/\[PROVIDER\]/g, config.provider)
    .replace(/\[PHYSICAL_INTERFACE\]/, config.physical_interface)
    .trim()
}

exports.format = (config) => {
  var ret = config.ppp ? exports.pppformat(config)
    : config.dhcp
    ? exports.dhcpFormat(config)
    : config.manual
    ? exports.manualFormat(config)
    : exports.staticFormat(config)

  if (Array.isArray(config.bridge_ports)) {
    config.bridge_opts = config.bridge_opts || {}
    var { stp } = config.bridge_opts
    ret += `\n  bridge_ports ${config.bridge_ports.join(' ')}`
    ret += `\n  bridge_stp ${stp ? 'on' : 'off'}`
  }

  return ret
}

